{"hash":"81ec4d9ab4175d29829b6a6a485f76dfe490fd0d","data":{"post":{"title":"snowflake-connector-python ReDoS","path":"/vulnerabilities/snowflake-connector-python-redos-xray-257185/","content":"<h2 id=\"summary\"><a href=\"#summary\" aria-hidden=\"true\" tabindex=\"-1\">Summary</a></h2>\n<p>Exponential ReDoS in snowflake-connector-python leads to denial of service</p>\n<h2 id=\"component\"><a href=\"#component\" aria-hidden=\"true\" tabindex=\"-1\">Component</a></h2>\n<p><a href=\"https://pypi.org/project/snowflake-connector-python\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">snowflake-connector-python</a></p>\n<h2 id=\"affected-versions\"><a href=\"#affected-versions\" aria-hidden=\"true\" tabindex=\"-1\">Affected versions</a></h2>\n<p>snowflake-connector-python (,)</p>\n<h2 id=\"description\"><a href=\"#description\" aria-hidden=\"true\" tabindex=\"-1\">Description</a></h2>\n<p>An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the snowflake-connector-python PyPI package, when an attacker is able to supply arbitrary input to the <code>snowflake-connector-python</code> method</p>\n<h2 id=\"poc\"><a href=\"#poc\" aria-hidden=\"true\" tabindex=\"-1\">PoC</a></h2>\n<p>No PoC is supplied for this issue</p>\n<h2 id=\"vulnerability-mitigations\"><a href=\"#vulnerability-mitigations\" aria-hidden=\"true\" tabindex=\"-1\">Vulnerability Mitigations</a></h2>\n<p>No mitigations are supplied for this issue</p>\n<h2 id=\"references\"><a href=\"#references\" aria-hidden=\"true\" tabindex=\"-1\">References</a></h2>\n<p><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-42965\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">NVD</a></p>\n","description":"CVE-2022-42965 Medium severity. Exponential ReDoS in snowflake-connector-python leads to denial of service","date_published":"2022-10-15","xray_id":"XRAY-257185","vul_id":"CVE-2022-42965","severity":"medium","discovered_by":"Denys Vozniuk","last_updated":"2022-10-15","cvss":5.9}},"context":{}}